import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

// Load environment variables (only if dotenv is available)
try {
	const dotenv = await import("dotenv");
	dotenv.config();
} catch (e) {
	// dotenv not installed or not needed (CI environments)
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Development vault configuration
const vaultPath = process.env.OBSIDIAN_VAULT_PATH;
const pluginId = process.env.PLUGIN_ID || "ODIN";
const vaultPluginDir = vaultPath ? path.join(vaultPath, ".obsidian", "plugins", pluginId) : null;

// Validate vault path in dev mode
if (!prod && !vaultPath) {
	console.warn("⚠️  OBSIDIAN_VAULT_PATH not set. Plugin will only build locally.");
	console.warn("   Set OBSIDIAN_VAULT_PATH in .env to enable hot-reload to your vault.");
}

// Ensure vault plugin directory exists
if (vaultPluginDir && !prod) {
	try {
		fs.mkdirSync(vaultPluginDir, { recursive: true });
		console.log(`✓ Building to vault: ${vaultPluginDir}`);
	} catch (err) {
		console.error(`❌ Failed to create vault plugin directory: ${err.message}`);
		process.exit(1);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/index.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: "copy-to-vault",
			setup(build) {
				build.onEnd(async (result) => {
					if (!vaultPluginDir || prod) return;
					
					if (result.errors.length > 0) {
						console.error("❌ Build failed, not copying to vault");
						return;
					}

					try {
						// Copy main.js
						fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
						
						// Copy manifest.json
						fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
						
						// Copy styles.css if it exists
						if (fs.existsSync("styles.css")) {
							fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));
						}
						
						console.log(`✓ Copied to vault at ${new Date().toLocaleTimeString()}`);
					} catch (err) {
						console.error(`❌ Failed to copy to vault: ${err.message}`);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	console.log("\n👁  Watching for changes...");
	console.log("   Edit files and save to trigger rebuild");
	console.log("   Press Ctrl+R (or Cmd+R) in Obsidian to reload the plugin\n");
}
